baseUrl = "http://www.chien-calme.com/"

languageCode = "fr-fr"
title = "Chien Calme"

theme = "younicorns"
description = "Des conseils pour avoir un chien calme"

[params]
    title="Des conseils pour maintenir l'équilibre et le bien-être de son chien "
	facebookPage = "https://www.facebook.com/chiencalme"
    twitterPage = "https://twitter.com/ChienCalme"
    twitterHandle = "ChienCalme"
    googlePage = "https://plus.google.com/u/0/117372126012522851863/posts"
    descriptionFooter = "Chien Calme est un site de conseils pour apprendre à accepter les petites bêtises de votre chien, et lui enseigner à les éviter avec des manières douces et naturelles."
    copyright = "Chien-Calme.com"
    address = "39 rue du Caire, 75002 Paris, FRANCE"
    phone = "+336 46 37 49 26"
    contactEmail = "contact@chien-calme.com"
    CommentsFacebook = true

###############
# Social
###############
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/ChienCalme"
    identifier = "twitter"
[[menu.social]]
    pre = "<i class='fa fa-facebook'></i>"
    url = "https://www.facebook.com/chiencalme"
    identifier = "facebook"
